# Form implementation generated from reading ui file 'tab_test.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 261, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tab1_pushButton = QtWidgets.QPushButton(self.tab_1)
        self.tab1_pushButton.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.tab1_pushButton.setObjectName("tab1_pushButton")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab2_label = QtWidgets.QLabel(self.tab_2)
        self.tab2_label.setGeometry(QtCore.QRect(0, 0, 101, 71))
        self.tab2_label.setObjectName("tab2_label")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab3_horizontalSlider = QtWidgets.QSlider(self.tab_3)
        self.tab3_horizontalSlider.setGeometry(QtCore.QRect(20, 20, 160, 22))
        self.tab3_horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.tab3_horizontalSlider.setObjectName("tab3_horizontalSlider")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tab1_pushButton.setText(_translate("Dialog", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "part 1"))
        self.tab2_label.setText(_translate("Dialog", "this is tab2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "part 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "part 3"))

print(__name__)
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window = Ui_Dialog()
    window.setupUi(MainWindow)
    MainWindow.show()
    app.exec()